-- MySQL Script generated by MySQL Workbench
-- Mon 05 Nov 2018 02:39:49 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema okanban
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `list` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'L\'identifiant de la liste',
  `name` VARCHAR(64) NOT NULL COMMENT 'Le nom de la liste',
  `page_order` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'L\'ordre de la liste dans la page',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `card` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'L\'identifiant du post-it',
  `title` VARCHAR(255) NOT NULL COMMENT 'Le titre/texte du post-it',
  `list_order` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'L\'ordre du post-it dans la liste',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `list_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC),
  INDEX `fk_card_list_idx` (`list_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `label` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'L\'identifiant du label',
  `name` VARCHAR(32) NOT NULL COMMENT 'Le nom du label',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `updated_at_UNIQUE` (`updated_at` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_has_label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `card_has_label` (
  `card_id` INT UNSIGNED NOT NULL,
  `label_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`card_id`, `label_id`),
  INDEX `fk_card_has_label_label1_idx` (`label_id` ASC),
  INDEX `fk_card_has_label_card1_idx` (`card_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
